<?php
/** @var History $block */

use Mageplaza\Affiliate\Block\Customer\Affiliate\History;

if (!$block->isEnable()) {
    $block->redirect();
}
?>

<div id="affiliate-dashboard" style="display: none">
    <div class="block block-dashboard-affiliate-history">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Affiliate Information')) ?></strong></div>
        <div class="block-content">
            <div class="box box-information">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Balance')) ?></span>
                </strong>
                <div class="box-content" id="affiliate-balance">
                </div>
            </div>
            <div class="box box-information">
                <div class="box-title" style="display: flex;align-items: center;gap:10px">
                    <strong><span><?= $block->escapeHtml(__('Refer :')) ?></span></strong>
                    <button style="background-color: #0095ff;
                    border: 1px solid transparent;
                    border-radius: 3px;
                    box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;
                    box-sizing: border-box;
                    color: #fff;
                    cursor: pointer;
                    display: inline-block;
                    font-size: 13px;
                    font-weight: 400;
                    line-height: 1.15385;
                    margin: 0;
                    outline: none;
                    padding: 8px .8em;
                    position: relative;
                    text-align: center;
                    text-decoration: none;
                    user-select: none;
                    -webkit-user-select: none;
                    touch-action: manipulation;
                    vertical-align: baseline;
                    white-space: nowrap;" data-link="" class="box-content"
                            id="refer-link">
                        Copy Link
                    </button>

                    <button style="background-color: #0095ff;
                    border: 1px solid transparent;
                    border-radius: 3px;
                    box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;
                    box-sizing: border-box;
                    color: #fff;
                    cursor: pointer;
                    display: inline-block;
                    font-size: 13px;
                    font-weight: 400;
                    line-height: 1.15385;
                    margin: 0;
                    outline: none;
                    padding: 8px .8em;
                    position: relative;
                    text-align: center;
                    text-decoration: none;
                    user-select: none;
                    -webkit-user-select: none;
                    touch-action: manipulation;
                    vertical-align: baseline;
                    " data-code="" class="box-content"
                            id="refer-code">
                        Copy Code
                    </button>
                </div>
            </div>
        </div>
    </div>


    <div id="affiliate-history" class="block block-dashboard-info">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Affiliate History')) ?></strong></div>
        <div class="table-wrapper orders-history">
            <table class="data table table-order-items history" id="my-affiliate-table">
                <thead>
                <tr>
                    <th scope="col" class="col "><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col "><?= $block->escapeHtml(__('Title')) ?></th>
                    <th scope="col" class="col "><?= $block->escapeHtml(__('Amount')) ?></th>
                    <th scope="col" class="col "><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col "><?= $block->escapeHtml(__('Date')) ?></th>
                </tr>
                </thead>
                <tbody id="affiliate-history-tbody">
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="block-content" id="not-active-account" style="display:none">
    <div class="box box-information message info empty" style="text-align: center">
        <span><?= $block->escapeHtml(__('Your account is not active ! Please contact to admin')) ?></span>
    </div>
</div>

<div class="referent-by" id="referent-by" style="display: none;margin:20px 0;">
    <div class="block-content">
        <div class="box box-information" style="display: flex;align-items: center;gap:3px;">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('You were referred by : ')) ?></span>
            </strong>
            <div class="box-content" id="referent-by-name">
            </div>
        </div>
        <a class="cancel-referent" href="<?= $block->cancelRefer() ?>" id="cancel-referent"
        ><?= $block->escapeHtml(__('Cancel Refer ')) ?></a>
    </div>
</div>

<!--Form register account -->
<div id="create-affiliate-account" style="display: none">
    <div>
        <?= $block->renderStaticBlock() ?>
    </div>

    <form action="<?= $block->getRegisterAction() ?>" method="post"
          id="form-create-account"
          class="form-create-account">
        <button style="background-color: #0095ff;
                    border: 1px solid transparent;
                    border-radius: 3px;
                    box-shadow: rgba(255, 255, 255, .4) 0 1px 0 0 inset;
                    box-sizing: border-box;
                    color: #fff;
                    cursor: pointer;
                    display: inline-block;
                    font-size: 16px;
                    font-weight: 400;
                    line-height: 1.15385;
                    margin: 0;
                    outline: none;
                    padding: 8px .8em;
                    position: relative;
                    text-align: center;
                    text-decoration: none;
                    user-select: none;
                    -webkit-user-select: none;
                    touch-action: manipulation;
                    vertical-align: baseline;
                    white-space: nowrap;" type="submit" class="button">
            <span><?= $block->escapeHtml(__('Register now')) ?></span>
        </button>
    </form>
</div>


